


dubbo:
  scan:
    base-packages: com.ldl.clouddubbo.provider.service
  application:
    name: dubbo-provider
  registry:
    address: nacos://192.168.226.128:8848
  protocol:
    name: dubbo
    port: 20880
spring:
  application:
    name: dubbo-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/myapp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8081
